In [1]:
from tensorflow.keras.preprocessing.text import one_hot

In [2]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [3]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [4]:
## Define the vocabulary size
voc_size=10000

In [5]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [6]:
### One Hot Representation
one_hot_repr=[one_hot(words,voc_size)for words in sent]
one_hot_repr

[[6877, 9323, 357, 7041],
 [6877, 9323, 357, 2196],
 [6877, 4760, 357, 7374],
 [3984, 2141, 9106, 9416, 7728],
 [3984, 2141, 9106, 9416, 4639],
 [528, 6877, 9615, 357, 450],
 [8214, 8692, 1806, 9416]]

In [7]:
## word Embedding Representation

from tensorflow.keras.layers import Embedding
#from tensorflow.keras.processing.sequence import pad_sequences
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [8]:
import numpy as np

In [9]:
sent_length=8
embedded_docs=pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 6877 9323  357 7041]
 [   0    0    0    0 6877 9323  357 2196]
 [   0    0    0    0 6877 4760  357 7374]
 [   0    0    0 3984 2141 9106 9416 7728]
 [   0    0    0 3984 2141 9106 9416 4639]
 [   0    0    0  528 6877 9615  357  450]
 [   0    0    0    0 8214 8692 1806 9416]]


In [10]:
## feature representation
dim=10

In [18]:
model=Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile('adam','mse')

c:\Sumit\PROJECTS\GenAI\venv\Lib\site-packages\keras\src\layers\core\embedding.py:97: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [20]:
##model.summary()
model.build(input_shape=(None, sent_length))
model.summary()

Model: "sequential_2"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_2 (Embedding)         │ (None, 8, 10)          │       100,000 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 100,000 (390.62 KB)

 Trainable params: 100,000 (390.62 KB)

 Non-trainable params: 0 (0.00 B)

In [21]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step


array([[[-1.98594686e-02, -1.91014297e-02, -4.14458662e-03,
         -2.21984871e-02,  3.07000615e-02, -4.68699336e-02,
          1.25559010e-02,  4.88882773e-02, -1.70811191e-02,
         -4.16476242e-02],
        [-1.98594686e-02, -1.91014297e-02, -4.14458662e-03,
         -2.21984871e-02,  3.07000615e-02, -4.68699336e-02,
          1.25559010e-02,  4.88882773e-02, -1.70811191e-02,
         -4.16476242e-02],
        [-1.98594686e-02, -1.91014297e-02, -4.14458662e-03,
         -2.21984871e-02,  3.07000615e-02, -4.68699336e-02,
          1.25559010e-02,  4.88882773e-02, -1.70811191e-02,
         -4.16476242e-02],
        [-1.98594686e-02, -1.91014297e-02, -4.14458662e-03,
         -2.21984871e-02,  3.07000615e-02, -4.68699336e-02,
          1.25559010e-02,  4.88882773e-02, -1.70811191e-02,
         -4.16476242e-02],
        [-4.59970012e-02,  1.75547712e-02, -4.94325161e-02,
         -8.88689607e-03,  2.66388170e-02, -1.17949247e-02,
         -7.86043331e-03,  2.49899663e-02, -2.357206

In [14]:
embedded_docs[0]

array([   0,    0,    0,    0, 6877, 9323,  357, 7041], dtype=int32)

In [22]:
## model.predict(embedded_docs[0])
import numpy as np
model.predict(np.array([embedded_docs[0]]))


1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step


array([[[-0.01985947, -0.01910143, -0.00414459, -0.02219849,
          0.03070006, -0.04686993,  0.0125559 ,  0.04888828,
         -0.01708112, -0.04164762],
        [-0.01985947, -0.01910143, -0.00414459, -0.02219849,
          0.03070006, -0.04686993,  0.0125559 ,  0.04888828,
         -0.01708112, -0.04164762],
        [-0.01985947, -0.01910143, -0.00414459, -0.02219849,
          0.03070006, -0.04686993,  0.0125559 ,  0.04888828,
         -0.01708112, -0.04164762],
        [-0.01985947, -0.01910143, -0.00414459, -0.02219849,
          0.03070006, -0.04686993,  0.0125559 ,  0.04888828,
         -0.01708112, -0.04164762],
        [-0.045997  ,  0.01755477, -0.04943252, -0.0088869 ,
          0.02663882, -0.01179492, -0.00786043,  0.02498997,
         -0.02357206, -0.00250898],
        [ 0.02542526, -0.03248069,  0.00212189,  0.02722054,
         -0.03270649,  0.02909495, -0.00495587, -0.01215781,
          0.02401657, -0.04122581],
        [ 0.04686728,  0.0317984 ,  0.01784981, -0.0